name: d_cloud
description: DCloud SDK for Dart / Flutter
version: 0.0.4+3

repository: https://github.com/nabeelparkardarwin/dcloud.git
issue_tracker: https://github.com/nabeelparkardarwin/dcloud/issues

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: ^4.0.0
  freezed_annotation: ^0.14.1
  json_annotation: ^4.0.1
  path: ^1.8.0

dev_dependencies:
  build_runner: ^1.12.2
  freezed: ^0.14.1+2
  json_serializable: ^4.1.0
  lint: ^1.5.3
  test: ^1.16.8
